{
    'name': "New_res_partner",
    'version': '17.0.1.0',
    'depends': ['base','sms','contacts','stock_barcode','hr'],
    'category': 'App',
    'application': False,
    'installable':True,
    'license': 'LGPL-3',
    'data': [
        'views/partner_barcode_report.xml',
        'views/new_res_partner_view.xml',
        'views/new_res_partner_company_view.xml',
        'views/new_res_partner_work_type_view.xml',
        'views/new_res_partner_function_view.xml',
        'security/ir.model.access.csv',
        'data/email_template.xml',
        'views/hr_employee_view.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'New_res_partner/static/src/css/custom_styles.css',
            'New_res_partner/static/src/js/barcode_dialog.js',
            'New_res_partner/static/src/js/partner_barcode.js',
            'New_res_partner/static/src/js/quagga.js',
            'New_res_partner/static/src/js/registry_barcode_partner.js',
            'New_res_partner/static/src/xml/barcode_dialog_templates.xml',
            'New_res_partner/static/src/xml/partner_barcode_templates.xml',
        ],
    },
    'installable': True,
    'application': True,
}
